name: Translate Readme Action
author: Willem van Heemstra
description: Translate the Readme to another language

inputs:
  LANG:
    description: 'The Language you want to translate to'
    required: false
    default: 'zh-CN'

runs:
  using: 'node16'
  main: 'dist/index.js'

branding:
  icon: book-open
  color: black
